(() => {
  const els = {
    shell: document.getElementById('shell'),
    sidebar: document.getElementById('sidebar'),
    sidebarOpen: document.getElementById('sidebarOpen'),
    sidebarClose: document.getElementById('sidebarClose'),
    sidebarScrim: document.getElementById('sidebarScrim'),
    newCheckBtn: document.getElementById('newCheckBtn'),
    historyList: document.getElementById('historyList'),
    historyEmpty: document.getElementById('historyEmpty'),
    pilotToggle: document.getElementById('pilotToggle'),
    pilotPanel: document.getElementById('pilotPanel'),
    thread: document.getElementById('thread'),
    emptyState: document.getElementById('emptyState'),
    emptyHeading: document.getElementById('emptyHeading'),
    emptySub: document.getElementById('emptySub'),
    emptyExamples: document.getElementById('emptyExamples'),
    message: document.getElementById('message'),
    checkBtn: document.getElementById('checkBtn'),
    pasteBtn: document.getElementById('pasteBtn'),
    charCount: document.getElementById('charCount'),
    status: document.getElementById('status'),
    statusDot: document.getElementById('status-dot'),
    baseUrl: document.getElementById('baseUrl'),
    langEn: document.getElementById('lang-en'),
    langHi: document.getElementById('lang-hi'),
    tplUser: document.getElementById('tpl-user-bubble'),
    tplLoading: document.getElementById('tpl-loading-bubble'),
  };

  const DEFAULT_API_BASE = 'https://axiom-41qr.onrender.com';

  if (!els.baseUrl.value || els.baseUrl.value === 'http://localhost:8000') {
    els.baseUrl.value = DEFAULT_API_BASE;
  }

  const labels = {
    en: {
      placeholder: 'Paste the forwarded message here…',
      heading: 'Verify before you forward',
      sub: "Paste a forwarded WhatsApp or social message below. Patterns checks it in English or Hindi against a verified claims database — no account, no signup.",
      tryOne: 'Try one',
      ready: 'Ready',
      checking: 'Checking…',
      matchConfidence: 'Match confidence',
      aiConfidence: 'AI confidence',
      curated: 'Verified match',
      aiVerdict: 'AI-generated verdict',
      aiNote: 'No verified fact-check exists for this yet, so this verdict was generated by AI, not a human fact-checker. Treat it as a starting point and use the checklist below to verify independently.',
      manualCheck: 'This touches money, health, elections, or communal tension — verify independently before trusting or forwarding it.',
      checklistHeading: 'Verify it yourself',
      checklistLead: "We couldn't confidently match this to a known claim. Work through this checklist before you believe or forward it.",
      source: 'Source',
      copy: 'Copy',
      copied: 'Copied',
      newCheck: 'New check',
      needText: 'Paste a message to check first.',
      networkError: "Couldn't reach the API. Check the endpoint in the sidebar and confirm the server is running.",
      serverError: 'Server error',
    },
    hi: {
      placeholder: 'यहाँ फॉरवर्ड किया गया संदेश पेस्ट करें…',
      heading: 'फॉरवर्ड करने से पहले जाँच लें',
      sub: 'नीचे कोई फॉरवर्ड किया गया व्हाट्सएप या सोशल मीडिया संदेश पेस्ट करें। Patterns इसे अंग्रेज़ी या हिंदी में एक सत्यापित डेटाबेस से जाँचता है — कोई अकाउंट या साइनअप नहीं।',
      tryOne: 'एक आज़माएँ',
      ready: 'तैयार',
      checking: 'जाँच हो रही है…',
      matchConfidence: 'मिलान विश्वास',
      aiConfidence: 'एआई विश्वास',
      curated: 'सत्यापित मिलान',
      aiVerdict: 'एआई-जनित निष्कर्ष',
      aiNote: 'इसके लिए अभी कोई सत्यापित तथ्य-जांच मौजूद नहीं है, इसलिए यह निष्कर्ष एआई द्वारा तैयार किया गया है, किसी मानव तथ्य-जांचकर्ता द्वारा नहीं। इसे शुरुआती बिंदु मानें और नीचे दी गई सूची से स्वयं सत्यापित करें।',
      manualCheck: 'यह पैसे, स्वास्थ्य, चुनाव या सांप्रदायिक तनाव से जुड़ा है — विश्वास करने या फॉरवर्ड करने से पहले स्वयं सत्यापित करें।',
      checklistHeading: 'स्वयं सत्यापित करें',
      checklistLead: 'हम इसे किसी ज्ञात दावे से आत्मविश्वास से नहीं मिला सके। विश्वास करने या फॉरवर्ड करने से पहले इस सूची से गुज़रें।',
      source: 'स्रोत',
      copy: 'कॉपी करें',
      copied: 'कॉपी हो गया',
      newCheck: 'नई जाँच',
      needText: 'पहले जाँचने के लिए एक संदेश पेस्ट करें।',
      networkError: 'API तक नहीं पहुँच सके। साइडबार में एंडपॉइंट जाँचें और सर्वर चालू है या नहीं देखें।',
      serverError: 'सर्वर त्रुटि',
    }
  };

  let lang = 'en';
  let historyCount = 0;

  // ---------- language ----------
  function setLang(n) {
    lang = n;
    els.message.placeholder = labels[n].placeholder;
    els.emptyHeading.textContent = labels[n].heading;
    els.emptySub.textContent = labels[n].sub;
    els.emptyExamples.querySelector('.empty-examples-label').textContent = labels[n].tryOne;
    els.newCheckBtn.lastChild.textContent = ' ' + labels[n].newCheck;
    document.querySelectorAll('.lang-btn').forEach(b => b.classList.toggle('active', b.dataset.lang === n));
    if (els.status.textContent === labels[n === 'en' ? 'hi' : 'en'].ready) setStatus(labels[n].ready);
  }

  // ---------- status ----------
  function setStatus(text, mode) {
    els.status.textContent = text;
    els.statusDot.className = 'status-dot' + (mode ? ' ' + mode : '');
  }

  // ---------- helpers ----------
  function escapeHtml(s) {
    if (!s) return '';
    return String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  }

  function verdictClass(verdict) {
    const v = (verdict || '').toLowerCase();
    return v === 'true' ? 'true' : v === 'false' ? 'false' : v === 'misleading' ? 'misleading' : 'unverified';
  }

  function scrollToBottom() {
    els.thread.scrollTo({ top: els.thread.scrollHeight, behavior: 'smooth' });
  }

  function hideEmptyState() {
    if (els.emptyState) { els.emptyState.remove(); }
  }

  // ---------- sidebar ----------
  function openSidebar() { els.shell.classList.add('sidebar-open'); }
  function closeSidebar() { els.shell.classList.remove('sidebar-open'); }
  els.sidebarOpen.addEventListener('click', openSidebar);
  els.sidebarClose.addEventListener('click', closeSidebar);
  els.sidebarScrim.addEventListener('click', closeSidebar);

  els.pilotToggle.addEventListener('click', () => {
    const open = els.pilotPanel.hasAttribute('hidden');
    if (open) { els.pilotPanel.removeAttribute('hidden'); } else { els.pilotPanel.setAttribute('hidden', ''); }
    els.pilotToggle.setAttribute('aria-expanded', String(open));
  });

  els.newCheckBtn.addEventListener('click', () => {
    els.message.value = '';
    autoGrow();
    els.message.focus();
    closeSidebar();
  });

  function addHistoryEntry(text, badgeClass, id) {
    els.historyEmpty && els.historyEmpty.remove();
    els.historyEmpty = null;
    historyCount += 1;
    const li = document.createElement('li');
    li.className = 'history-item';
    const dotColor = {
      true: 'var(--stamp-green)', false: 'var(--stamp-red)',
      misleading: 'var(--stamp-amber)', unverified: 'var(--stamp-grey)'
    }[badgeClass] || 'var(--stamp-grey)';
    li.innerHTML = `<span class="history-dot" style="background:${dotColor}"></span><span class="history-snippet"></span>`;
    li.querySelector('.history-snippet').textContent = text.slice(0, 46) + (text.length > 46 ? '…' : '');
    li.addEventListener('click', () => {
      document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      closeSidebar();
    });
    els.historyList.prepend(li);
  }

  // ---------- textarea ----------
  function autoGrow() {
    els.message.style.height = 'auto';
    els.message.style.height = Math.min(els.message.scrollHeight, 140) + 'px';
    els.charCount.textContent = els.message.value.length;
  }
  els.message.addEventListener('input', autoGrow);

  // ---------- clipboard paste (the "shortcut" quick-paste) ----------
  els.pasteBtn.addEventListener('click', async () => {
    try {
      const text = await navigator.clipboard.readText();
      if (text) {
        els.message.value = text;
        autoGrow();
        els.message.focus();
      }
    } catch (err) {
      setStatus('Clipboard access blocked — paste manually (Ctrl/Cmd+V).', 'error');
      els.message.focus();
    }
  });

  // ---------- rendering ----------
  function confidenceBlock(label, pct) {
    return `
      <div class="confidence-block">
        <div class="confidence-head"><span>${label}</span><span>${pct}%</span></div>
        <div class="confidence-track"><div class="confidence-fill" style="width:${pct}%"></div></div>
      </div>`;
  }

  function copyButton(text) {
    const btn = document.createElement('button');
    btn.className = 'copy-btn';
    btn.textContent = labels[lang].copy;
    btn.addEventListener('click', async () => {
      try {
        await navigator.clipboard.writeText(text);
        btn.textContent = labels[lang].copied;
        btn.classList.add('copied');
        setTimeout(() => { btn.textContent = labels[lang].copy; btn.classList.remove('copied'); }, 1600);
      } catch { /* ignore */ }
    });
    return btn;
  }

  function renderMatched(data, rowId) {
    const badgeClass = verdictClass(data.verdict);
    const pct = Math.round((data.confidence ?? 0) * 100);

    const row = document.createElement('div');
    row.className = 'msg msg-assistant';
    row.id = rowId;
    const card = document.createElement('div');
    card.className = 'dossier';
    card.innerHTML = `
      <div class="dossier-head">
        <span class="stamp ${badgeClass}">${escapeHtml(data.verdict)}</span>
        <span class="source-tag">${labels[lang].curated}</span>
      </div>
      <div class="dossier-body">
        ${data.matched_claim_text ? `<p class="dossier-quote">${escapeHtml(data.matched_claim_text)}</p>` : ''}
        <p class="dossier-explanation">${escapeHtml(data.explanation)}</p>
        ${confidenceBlock(labels[lang].matchConfidence, pct)}
        <div class="dossier-actions">
          ${data.source_url ? `<a class="dossier-link" href="${escapeHtml(data.source_url)}" target="_blank" rel="noopener">${labels[lang].source} ↗</a>` : ''}
        </div>
      </div>`;
    card.querySelector('.dossier-actions').appendChild(copyButton(data.explanation || ''));
    row.appendChild(card);
    els.thread.appendChild(row);
    addHistoryEntry(data.matched_claim_text || data.explanation || '', badgeClass, rowId);
  }

  function renderLLM(data, rowId) {
    const badgeClass = verdictClass(data.verdict);
    const confMap = { high: 85, medium: 55, low: 25 };
    const pct = confMap[data.confidence_label] ?? 40;

    const row = document.createElement('div');
    row.className = 'msg msg-assistant';
    row.id = rowId;
    const card = document.createElement('div');
    card.className = 'dossier';
    card.innerHTML = `
      <div class="dossier-head">
        <span class="stamp ${badgeClass}">${escapeHtml(data.verdict)}</span>
        <span class="source-tag">${labels[lang].aiVerdict}</span>
      </div>
      <div class="dossier-body">
        <p class="dossier-ai-note">${labels[lang].aiNote}</p>
        <p class="dossier-explanation">${escapeHtml(data.explanation)}</p>
        ${confidenceBlock(labels[lang].aiConfidence, pct)}
        ${data.recommend_manual_check ? `<div class="manual-check-warning">${labels[lang].manualCheck}</div>` : ''}
        <div class="dossier-actions"></div>
      </div>`;
    card.querySelector('.dossier-actions').appendChild(copyButton(data.explanation || ''));
    row.appendChild(card);
    els.thread.appendChild(row);

    if (Array.isArray(data.checklist) && data.checklist.length) appendChecklist(data.checklist);
    addHistoryEntry(data.explanation || '', badgeClass, rowId);
  }

  function renderUnmatched(data, rowId) {
    const row = document.createElement('div');
    row.className = 'msg msg-assistant';
    row.id = rowId;
    const card = document.createElement('div');
    card.className = 'checklist-card';
    card.innerHTML = `<p class="checklist-lead">${escapeHtml(data.message || labels[lang].checklistLead)}</p>`;
    row.appendChild(card);
    els.thread.appendChild(row);
    if (Array.isArray(data.checklist)) appendChecklist(data.checklist, card);
    addHistoryEntry(data.message || 'Unmatched — checklist given', 'unverified', rowId);
  }

  function appendChecklist(items, intoCard) {
    let card = intoCard;
    if (!card) {
      const row = document.createElement('div');
      row.className = 'msg msg-assistant';
      card = document.createElement('div');
      card.className = 'checklist-card';
      row.appendChild(card);
      els.thread.appendChild(row);
    }
    const h = document.createElement('p');
    h.className = 'checklist-heading';
    h.textContent = labels[lang].checklistHeading;
    const ol = document.createElement('ol');
    ol.className = 'checklist';
    items.forEach(item => { const li = document.createElement('li'); li.textContent = item; ol.appendChild(li); });
    card.appendChild(h);
    card.appendChild(ol);
  }

  function renderError(text) {
    const row = document.createElement('div');
    row.className = 'msg msg-assistant';
    const card = document.createElement('div');
    card.className = 'error-card';
    card.textContent = text;
    row.appendChild(card);
    els.thread.appendChild(row);
  }

  // ---------- send flow ----------
  async function checkMessage() {
    const text = els.message.value.trim();
    if (!text) { setStatus(labels[lang].needText, 'error'); return; }
    hideEmptyState();

    // user bubble
    const userNode = els.tplUser.content.cloneNode(true);
    userNode.querySelector('.bubble-text').textContent = text;
    els.thread.appendChild(userNode);

    // loading bubble
    const loadingNode = els.tplLoading.content.cloneNode(true);
    const loadingEl = loadingNode.querySelector('.msg');
    els.thread.appendChild(loadingNode);
    scrollToBottom();

    els.message.value = '';
    autoGrow();
    els.checkBtn.disabled = true;
    setStatus(labels[lang].checking, 'busy');

    const baseUrl = (els.baseUrl.value || DEFAULT_API_BASE).replace(/\/+$/, '');
    const url = baseUrl + '/api/verify';
    const rowId = 'r' + Date.now();

    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text })
      });
      document.querySelector('.msg-loading')?.remove();

      if (!res.ok) {
        setStatus(labels[lang].serverError + ': ' + res.status, 'error');
        const errText = await res.text();
        renderError(errText || labels[lang].serverError);
        return;
      }
      const data = await res.json();
      setStatus(labels[lang].ready, 'done');
      if (data && data.matched === true) renderMatched(data, rowId);
      else if (data && data.matched === false && data.source === 'llm') renderLLM(data, rowId);
      else if (data && data.matched === false) renderUnmatched(data, rowId);
      else renderError(JSON.stringify(data));
    } catch (err) {
      document.querySelector('.msg-loading')?.remove();
      setStatus('Network error', 'error');
      renderError(labels[lang].networkError);
    } finally {
      els.checkBtn.disabled = false;
      scrollToBottom();
    }
  }

  els.checkBtn.addEventListener('click', checkMessage);
  els.message.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && !e.shiftKey && !e.ctrlKey && !e.metaKey && window.innerWidth >= 900) {
      e.preventDefault();
      checkMessage();
    } else if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      checkMessage();
    }
  });

  els.langEn.addEventListener('click', () => setLang('en'));
  els.langHi.addEventListener('click', () => setLang('hi'));

  // ---------- example chips ----------
  document.querySelectorAll('.example-chip').forEach(chip => {
    chip.addEventListener('click', () => {
      els.message.value = chip.dataset.example;
      autoGrow();
      checkMessage();
    });
  });

  // ---------- share-target / shortcut prefill ----------
  // When "Patterns" is installed as a PWA and set as an Android share target,
  // the OS share sheet lands here as /?text=... . We prefill and auto-check.
  (function handleSharedText() {
    const params = new URLSearchParams(window.location.search);
    const shared = params.get('text') || params.get('url') || params.get('title');
    if (shared) {
      els.message.value = shared;
      autoGrow();
      // clean the URL so a refresh doesn't re-trigger
      window.history.replaceState({}, '', window.location.pathname);
      checkMessage();
    }
  })();

  // ---------- PWA install (needed for the share-target shortcut) ----------
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('sw.js').catch(() => { /* ignore on unsupported hosts */ });
  }

  setLang('en');
  setStatus(labels[lang].ready);
  autoGrow();
})();
